import {
  Activity,
  ArchiveRestore,
  ArrowRight,
  BellRing,
  Box,
  Boxes,
  BrainCircuit,
  Cable,
  CloudCog,
  Code2,
  Database,
  DatabaseZap,
  FolderTree,
  GitBranch,
  Globe2,
  Hammer,
  HardDrive,
  Images,
  KeyRound,
  Layers3,
  Logs,
  MessageSquareMore,
  Monitor,
  Network,
  RadioTower,
  Rocket,
  Route,
  ScrollText,
  Search,
  Server,
  ServerCog,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Store,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import { serviceLogos } from "@/lib/service-logos";

export type ServiceCategory =
  | "Compute"
  | "Containers"
  | "Storage"
  | "Networking"
  | "Databases"
  | "Security"
  | "Billing"
  | "Monitoring";

export type ServiceCatalogItem = {
  name: string;
  shortName: string;
  description: string;
  href?: string;
  logo?: string;
  status?: string;
  icon: LucideIcon;
  aliases: string[];
  searchCategory?: string;
};

export const serviceCatalog: Record<ServiceCategory, ServiceCatalogItem[]> = {
  Compute: [
    {
      name: "Elastic Cloud Server",
      shortName: "ECS",
      description:
        "Virtual machines with flexible compute, images, disks, and networking.",
      href: "/services/ecs",
      logo: serviceLogos.ECS,
      status: "Available",
      icon: Server,
      aliases: ["vm", "virtual machine", "compute", "instance"],
      searchCategory: "Compute",
    },
    {
      name: "Bare Metal Server",
      shortName: "BMS",
      description:
        "Dedicated physical servers for high performance and isolation.",
      href: "/services/bms",
      logo: serviceLogos.BMS,
      status: "Available",
      icon: Server,
      aliases: ["bare metal", "physical server", "dedicated server", "compute"],
      searchCategory: "Compute",
    },
    {
      name: "Dedicated Host",
      shortName: "DeH",
      description:
        "Dedicated physical hosts for ECS placement and compliance needs.",
      href: "/services/deh",
      logo: serviceLogos.DEH,
      status: "Available",
      icon: Server,
      aliases: ["dedicated host", "host pool", "byol", "isolation", "capacity"],
      searchCategory: "Compute",
    },
    {
      name: "Auto Scaling",
      shortName: "AS",
      description:
        "Scaling groups, member instances, scaling policies, and launch configurations.",
      href: "/services/as",
      logo: serviceLogos.AS,
      status: "Available",
      icon: Activity,
      aliases: ["scaling", "autoscale", "capacity"],
      searchCategory: "Compute",
    },
    {
      name: "FunctionGraph",
      shortName: "FunctionGraph",
      description:
        "Event-driven serverless functions for APIs, automation, and cloud workflows.",
      href: "/services/functiongraph",
      logo: serviceLogos.FG,
      status: "Available",
      icon: Code2,
      aliases: [
        "function",
        "serverless",
        "lambda",
        "faas",
        "event",
        "workflow",
      ],
      searchCategory: "Compute",
    },
    {
      name: "Image Management Service",
      shortName: "IMS",
      description: "Create, manage, and share system and private images.",
      href: "/services/ims",
      logo: serviceLogos.IMS,
      status: "Available",
      icon: Images,
      aliases: ["image", "ami", "os image", "private image"],
      searchCategory: "Compute",
    },
    {
      name: "Cloud Phone Host",
      shortName: "CPH",
      description:
        "Cloud-hosted mobile device resources for mobile apps and testing.",
      href: "/services/cph",
      logo: serviceLogos.CPH,
      status: "Available",
      icon: Smartphone,
      aliases: [
        "cloud phone",
        "android",
        "mobile testing",
        "phone server",
        "cph",
      ],
      searchCategory: "Compute",
    },
    {
      name: "Server Migration Service",
      shortName: "SMS",
      description:
        "Server migration tasks, source mappings, target servers, and progress state.",
      href: "/services/sms",
      logo: serviceLogos.SMS,
      status: "Available",
      icon: Server,
      aliases: [
        "server migration",
        "sms",
        "migration task",
        "source server",
        "target server",
      ],
      searchCategory: "Migration",
    },
    {
      name: "Huawei Cloud Flexus",
      shortName: "Flexus",
      description:
        "Read-only Flexus compute and database resource rollup from documented inventory APIs.",
      href: "/services/flexus",
      logo: serviceLogos.FLEXUS,
      status: "Available",
      icon: ServerCog,
      aliases: [
        "flexus",
        "hcss",
        "hecs",
        "lightweight server",
        "flexus x",
        "flexus l",
      ],
      searchCategory: "Compute",
    },
    {
      name: "CodeArts Repo",
      shortName: "CodeArts Repo",
      description:
        "Source repositories, default branches, visibility, and clone URLs.",
      href: "/services/codearts-repo",
      logo: serviceLogos.CODEARTS_REPO,
      status: "Available",
      icon: GitBranch,
      aliases: ["repo", "codearts repo", "repository", "git", "codehub"],
      searchCategory: "Developer",
    },
    {
      name: "CodeArts Build",
      shortName: "CodeArts Build",
      description:
        "Build tasks, latest execution status, triggers, branches, and repository linkage.",
      href: "/services/codearts-build",
      logo: serviceLogos.CODEARTS_BUILD,
      status: "Available",
      icon: Hammer,
      aliases: ["build", "codearts build", "ci", "build task", "compile"],
      searchCategory: "Developer",
    },
    {
      name: "CodeArts Pipeline",
      shortName: "CodeArts Pipeline",
      description:
        "CI/CD pipelines, execution status, groups, sources, and latest run metadata.",
      href: "/services/codearts-pipeline",
      logo: serviceLogos.CODEARTS_PIPELINE,
      status: "Available",
      icon: Workflow,
      aliases: ["pipeline", "codearts pipeline", "cicd", "workflow", "release"],
      searchCategory: "Developer",
    },
    {
      name: "CodeArts Deploy",
      shortName: "CodeArts Deploy",
      description:
        "Deployment applications, groups, owners, and lifecycle timestamps.",
      href: "/services/codearts-deploy",
      logo: serviceLogos.CODEARTS_DEPLOY,
      status: "Available",
      icon: Rocket,
      aliases: [
        "deploy",
        "codearts deploy",
        "deployment",
        "application release",
      ],
      searchCategory: "Developer",
    },
    {
      name: "ServiceStage",
      shortName: "ServiceStage",
      description:
        "Application management inventory with components, creators, and enterprise project scope.",
      href: "/services/servicestage",
      logo: serviceLogos.SERVICESTAGE,
      status: "Available",
      icon: Boxes,
      aliases: [
        "servicestage",
        "application management",
        "component",
        "environment",
        "microservice",
      ],
      searchCategory: "Application",
    },
  ],
  Containers: [
    {
      name: "Cloud Container Engine",
      shortName: "CCE",
      description:
        "Managed Kubernetes clusters for containerized applications.",
      href: "/services/cce",
      logo: serviceLogos.CCE,
      status: "Available",
      icon: Layers3,
      aliases: ["kubernetes", "k8s", "containers", "cluster"],
      searchCategory: "Containers",
    },
    {
      name: "Software Repository for Container",
      shortName: "SWR",
      description:
        "Basic edition container image repositories, image tags, digests, and pull commands.",
      href: "/services/swr",
      logo: serviceLogos.SWR,
      status: "Available",
      icon: Code2,
      aliases: [
        "registry",
        "container registry",
        "image",
        "docker",
        "artifact",
      ],
      searchCategory: "Containers",
    },
    {
      name: "Cloud Container Instance",
      shortName: "CCI",
      description: "Serverless container runtime without cluster management.",
      href: "/services/cci",
      logo: serviceLogos.CCI,
      status: "Available",
      icon: Layers3,
      aliases: ["serverless containers", "pod", "namespace", "cci2"],
      searchCategory: "Containers",
    },
    {
      name: "Application Service Mesh",
      shortName: "ASM",
      description:
        "Service mesh traffic governance and observability for microservices.",
      href: "/services/asm",
      status: "Available",
      icon: Boxes,
      aliases: [],
    },
  ],
  Storage: [
    {
      name: "Object Storage Service",
      shortName: "OBS",
      description:
        "Object buckets for files, backups, static assets, and data lakes.",
      href: "/services/obs",
      logo: serviceLogos.OBS,
      status: "Available",
      icon: Box,
      aliases: ["bucket", "object", "storage", "s3"],
      searchCategory: "Storage",
    },
    {
      name: "Elastic Volume Service",
      shortName: "EVS",
      description:
        "Block storage disks for ECS, databases, and stateful workloads.",
      href: "/services/evs",
      logo: serviceLogos.EVS,
      status: "Available",
      icon: HardDrive,
      aliases: ["disk", "volume", "block storage"],
      searchCategory: "Storage",
    },
    {
      name: "Scalable File Service",
      shortName: "SFS",
      description:
        "Shared file storage for multiple cloud servers and containers.",
      href: "/services/sfs",
      logo: serviceLogos.SFS,
      status: "Available",
      icon: FolderTree,
      aliases: ["file", "nfs", "shared storage"],
      searchCategory: "Storage",
    },
    {
      name: "Cloud Backup and Recovery",
      shortName: "CBR",
      description:
        "Backup and restore for servers, disks, file systems, and apps.",
      href: "/services/cbr",
      logo: serviceLogos.CBR,
      status: "Available",
      icon: ArchiveRestore,
      aliases: ["backup", "vault", "restore", "snapshot"],
      searchCategory: "Storage",
    },
    {
      name: "Data Express Service",
      shortName: "DES",
      description: "Offline migration service for large-scale data transfer.",
      logo: serviceLogos.DES,
      status: "Catalog",
      icon: Boxes,
      aliases: [],
    },
    {
      name: "Object Storage Migration Service",
      shortName: "OMS",
      description:
        "Object migration tasks, source clouds, bucket targets, and transfer progress.",
      href: "/services/oms",
      logo: serviceLogos.OMS,
      status: "Available",
      icon: Box,
      aliases: [
        "object migration",
        "bucket migration",
        "oms",
        "sync task",
        "source cloud",
      ],
      searchCategory: "Migration",
    },
    {
      name: "Storage Disaster Recovery Service",
      shortName: "SDRS",
      description:
        "Protected instances, production/DR server mapping, and replication pairs.",
      href: "/services/sdrs",
      logo: serviceLogos.SDRS,
      status: "Available",
      icon: ArchiveRestore,
      aliases: [
        "disaster recovery",
        "sdrs",
        "protected instance",
        "replication pair",
        "dr",
      ],
      searchCategory: "Migration",
    },
    {
      name: "Migration Center",
      shortName: "MGC",
      description:
        "Unified migration-center rollup across server, object, and data migration assets.",
      href: "/services/mgc",
      logo: serviceLogos.MGC,
      status: "Available",
      icon: Route,
      aliases: [
        "migration center",
        "mgc",
        "migration workflow",
        "application migration",
        "storage migration",
      ],
      searchCategory: "Migration",
    },
  ],
  Networking: [
    {
      name: "Virtual Private Cloud",
      shortName: "VPC",
      description:
        "Isolated private networks, subnets, routes, and security groups.",
      href: "/services/network",
      logo: serviceLogos.VPC,
      status: "Available",
      icon: Network,
      aliases: ["network", "subnet", "route", "security group"],
      searchCategory: "Networking",
    },
    {
      name: "Elastic IP",
      shortName: "EIP",
      description:
        "Public IP addresses and bandwidth for internet-facing resources.",
      href: "/services/eip",
      logo: serviceLogos.EIP,
      status: "Available",
      icon: Globe2,
      aliases: ["public ip", "internet ip", "ipv4"],
      searchCategory: "Networking",
    },
    {
      name: "Elastic Load Balance",
      shortName: "ELB",
      description:
        "Traffic distribution across ECS, CCE, and private backend pools.",
      href: "/services/elb",
      logo: serviceLogos.ELB,
      status: "Available",
      icon: CloudCog,
      aliases: ["load balancer", "traffic", "balancing"],
      searchCategory: "Networking",
    },
    {
      name: "NAT Gateway",
      shortName: "NAT",
      description: "SNAT and DNAT connectivity for private subnet resources.",
      href: "/services/nat",
      logo: serviceLogos.NAT,
      status: "Available",
      icon: Route,
      aliases: ["snat", "dnat", "nat gateway", "egress"],
      searchCategory: "Networking",
    },
    {
      name: "Direct Connect",
      shortName: "DC",
      description:
        "Dedicated private connectivity between on-premises and Huawei Cloud.",
      href: "/services/direct-connect",
      logo: serviceLogos.DC,
      status: "Available",
      icon: Cable,
      aliases: [
        "direct connect",
        "dedicated line",
        "private circuit",
        "connection",
      ],
      searchCategory: "Networking",
    },
    {
      name: "Enterprise Router",
      shortName: "ER",
      description:
        "Cloud hub routing for VPC, VPN, Direct Connect, and peering attachments.",
      href: "/services/enterprise-router",
      logo: serviceLogos.ER,
      status: "Available",
      icon: Route,
      aliases: [
        "enterprise router",
        "er",
        "cloud router",
        "routing hub",
        "asn",
      ],
      searchCategory: "Networking",
    },
    {
      name: "Virtual Private Network",
      shortName: "VPN",
      description:
        "Encrypted site-to-site connectivity for VPCs and remote networks.",
      href: "/services/vpn",
      logo: serviceLogos.VPN,
      status: "Available",
      icon: Cable,
      aliases: ["ipsec", "site to site", "tunnel", "customer gateway"],
      searchCategory: "Networking",
    },
    {
      name: "VPC Endpoint",
      shortName: "VPCEP",
      description:
        "Private access to cloud services without internet exposure.",
      href: "/services/vpc-endpoint",
      logo: serviceLogos.VPCEP,
      status: "Available",
      icon: Network,
      aliases: [
        "vpc endpoint",
        "privatelink",
        "private service",
        "endpoint service",
      ],
      searchCategory: "Networking",
    },
    {
      name: "Cloud Connect",
      shortName: "CC",
      href: "/services/cc",
      description:
        "Global private network connectivity across regions and VPCs.",
      logo: serviceLogos.CC,
      status: "Available",
      icon: Boxes,
      aliases: [],
    },
    {
      name: "Domain Name Service",
      shortName: "DNS",
      description: "Public and private DNS zones and record management.",
      href: "/services/dns",
      logo: serviceLogos.DNS,
      status: "Available",
      icon: Globe2,
      aliases: ["domain", "zone", "record", "ttl", "nameserver"],
      searchCategory: "Networking",
    },
    {
      name: "Content Delivery Network",
      shortName: "CDN",
      description: "Acceleration domains, CNAMEs, origins, and service areas.",
      href: "/services/cdn",
      logo: serviceLogos.CDN,
      status: "Available",
      icon: CloudCog,
      aliases: ["content delivery", "acceleration", "origin", "cname", "edge"],
      searchCategory: "Networking",
    },
    {
      name: "API Gateway",
      shortName: "APIG",
      description: "Dedicated API gateways, VPC placement, and public access.",
      href: "/services/apig",
      logo: serviceLogos.APIG,
      status: "Available",
      icon: CloudCog,
      aliases: ["api", "gateway", "dedicated gateway", "apigw"],
      searchCategory: "Networking",
    },

    {
      name: "Security Groups",
      shortName: "SG",
      searchCategory: "Networking",
      description:
        "Stateful virtual firewalls for ECS, CCE, and database traffic.",
      href: "/services/network",
      icon: ShieldCheck,
      logo: serviceLogos.VPC,
      aliases: ["security group", "firewall", "inbound", "outbound", "rules"],
      status: "Available",
    },
    {
      name: "Subnets",
      shortName: "Subnet",
      searchCategory: "Networking",
      description: "IP ranges and gateway configuration inside VPC networks.",
      href: "/services/network",
      icon: Network,
      logo: serviceLogos.VPC,
      aliases: ["cidr", "gateway", "ip range", "network segment"],
      status: "Available",
    },
  ],
  Databases: [
    {
      name: "Distributed Message Service for RabbitMQ",
      shortName: "DMS RabbitMQ",
      description:
        "RabbitMQ instances, connection endpoints, storage, and network placement.",
      href: "/services/dms-rabbitmq",
      status: "Available",
      icon: MessageSquareMore,
      aliases: ["rabbitmq", "amqp", "queue", "message broker"],
      searchCategory: "Middleware",
    },
    {
      name: "Distributed Message Service for RocketMQ",
      shortName: "DMS RocketMQ",
      description:
        "RocketMQ instances, NameServer endpoints, broker capacity, and network placement.",
      href: "/services/dms-rocketmq",
      status: "Available",
      icon: MessageSquareMore,
      aliases: ["rocketmq", "reliability", "message queue", "message broker"],
      searchCategory: "Middleware",
    },
    {
      name: "Relational Database Service",
      shortName: "RDS",
      description: "Managed MySQL, PostgreSQL, and SQL Server databases.",
      href: "/services/rds",
      logo: serviceLogos.RDS,
      status: "Available",
      icon: Database,
      aliases: ["mysql", "postgres", "sql", "database"],
      searchCategory: "Database",
    },
    {
      name: "GaussDB",
      shortName: "GaussDB",
      description: "Enterprise distributed relational database service.",
      href: "/services/gaussdb",
      logo: serviceLogos.GAUSSDB,
      status: "Available",
      icon: Database,
      aliases: ["opengauss", "distributed database", "enterprise database"],
      searchCategory: "Databases",
    },
    {
      name: "Document Database Service",
      shortName: "DDS",
      description: "MongoDB-compatible document database service.",
      href: "/services/dds",
      logo: serviceLogos.DDS,
      status: "Available",
      icon: Database,
      aliases: ["mongodb", "document database", "replica set", "cluster"],
      searchCategory: "Databases",
    },
    {
      name: "Distributed Cache Service",
      shortName: "DCS",
      description: "Managed Redis and Memcached cache instances.",
      href: "/services/dcs",
      logo: serviceLogos.DCS,
      status: "Available",
      icon: DatabaseZap,
      aliases: ["redis", "memcached", "cache"],
      searchCategory: "Databases",
    },
    {
      name: "Distributed Message Service for Kafka",
      shortName: "DMS Kafka",
      description:
        "Managed Kafka instances, brokers, partitions, endpoints, and storage.",
      href: "/services/dms-kafka",
      logo: serviceLogos.DMS_KAFKA,
      status: "Available",
      icon: MessageSquareMore,
      aliases: ["kafka", "broker", "topic", "message queue", "streaming"],
      searchCategory: "Databases",
    },
    {
      name: "Data Replication Service",
      shortName: "DRS",
      description:
        "Database migration, synchronization, and disaster recovery.",
      href: "/services/drs",
      logo: serviceLogos.DRS,
      status: "Available",
      icon: ArrowRight,
      aliases: ["migration", "replication", "sync", "disaster recovery"],
      searchCategory: "Databases",
    },
    {
      name: "TaurusDB",
      shortName: "TaurusDB",
      description: "MySQL-compatible cloud-native database instances.",
      href: "/services/taurusdb",
      logo: serviceLogos.GAUSSDB,
      status: "Available",
      icon: DatabaseZap,
      aliases: ["gaussdb mysql", "mysql", "taurus", "cloud native database"],
      searchCategory: "Databases",
    },
    {
      name: "GeminiDB",
      shortName: "GeminiDB",
      description:
        "Multi-model NoSQL database instances for Cassandra, Mongo, Influx, and Redis APIs.",
      href: "/services/geminidb",
      logo: serviceLogos.GAUSSDB,
      status: "Available",
      icon: Database,
      aliases: [
        "nosql",
        "cassandra",
        "mongo",
        "influx",
        "redis",
        "multi model",
      ],
      searchCategory: "Databases",
    },
    {
      name: "ModelArts",
      shortName: "ModelArts",
      description:
        "AI development notebooks, workspaces, images, and compute resource pools.",
      href: "/services/modelarts",
      logo: serviceLogos.MODELARTS,
      status: "Available",
      icon: BrainCircuit,
      aliases: [
        "ai",
        "machine learning",
        "notebook",
        "model",
        "training",
        "workspace",
      ],
      searchCategory: "Analytics",
    },
    {
      name: "Data Lake Insight",
      shortName: "DLI",
      description:
        "Serverless SQL, Spark, and Flink queues for lakehouse analytics.",
      href: "/services/dli",
      logo: serviceLogos.DLI,
      status: "Available",
      icon: DatabaseZap,
      aliases: ["lakehouse", "sql queue", "spark", "flink", "queue", "cu"],
      searchCategory: "Analytics",
    },
    {
      name: "MapReduce Service",
      shortName: "MRS",
      description: "Managed Hadoop, Spark, HBase, Hive, and big data clusters.",
      href: "/services/mrs",
      logo: serviceLogos.MRS,
      status: "Available",
      icon: Layers3,
      aliases: ["hadoop", "spark", "hbase", "hive", "big data", "cluster"],
      searchCategory: "Analytics",
    },
    {
      name: "Data Warehouse Service",
      shortName: "DWS",
      description: "Cloud data warehouse for analytics workloads.",
      href: "/services/dws",
      logo: serviceLogos.DWS,
      status: "Available",
      icon: Database,
      aliases: ["warehouse", "gaussdb dws", "analytics", "mpp", "cluster"],
      searchCategory: "Analytics",
    },
    {
      name: "Cloud Search Service",
      shortName: "CSS",
      description: "Elasticsearch and OpenSearch-compatible search clusters.",
      href: "/services/css",
      logo: serviceLogos.CSS,
      status: "Available",
      icon: Search,
      aliases: ["elasticsearch", "opensearch", "search", "index", "kibana"],
      searchCategory: "Search",
    },
    {
      name: "Cloud Data Migration",
      shortName: "CDM",
      description:
        "Data migration clusters, node topology, runtime status, and access endpoints.",
      href: "/services/cdm",
      logo: serviceLogos.CDM,
      status: "Available",
      icon: DatabaseZap,
      aliases: [
        "data migration",
        "cdm",
        "etl",
        "migration cluster",
        "data integration",
      ],
      searchCategory: "Analytics",
    },
    {
      name: "DataArts Studio",
      shortName: "DataArts",
      description:
        "Data governance instances, editions, workspaces, and lifecycle status.",
      href: "/services/dataarts",
      logo: serviceLogos.DATAARTS,
      status: "Available",
      icon: FolderTree,
      aliases: [
        "dataarts",
        "data governance",
        "data catalog",
        "data factory",
        "workspace",
      ],
      searchCategory: "Analytics",
    },
  ],
  Security: [
    {
      name: "Identity and Access Management",
      shortName: "IAM",
      description: "Users, groups, policies, roles, and access keys.",
      href: "/services/iam",
      logo: serviceLogos.IAM,
      status: "Available",
      icon: KeyRound,
      aliases: ["identity", "permission", "policy", "user", "access"],
      searchCategory: "Security",
    },
    {
      name: "Web Application Firewall",
      shortName: "WAF",
      description:
        "Protection for websites and APIs against common web attacks.",
      href: "/services/waf",
      logo: serviceLogos.WAF,
      status: "Available",
      icon: ShieldCheck,
      aliases: [
        "firewall",
        "web security",
        "api protection",
        "protected host",
        "policy",
      ],
      searchCategory: "Security",
    },
    {
      name: "Data Encryption Workshop",
      shortName: "DEW",
      description: "Key management, secrets, and encryption capabilities.",
      href: "/services/dew",
      logo: serviceLogos.DEW,
      status: "Available",
      icon: KeyRound,
      aliases: ["kms", "key", "encryption", "secrets", "csms", "rotation"],
      searchCategory: "Security",
    },
    {
      name: "Cloud Bastion Host",
      shortName: "CBH",
      description:
        "Bastion host instances, versions, access addresses, and upgrade posture.",
      href: "/services/cbh",
      logo: serviceLogos.CBH,
      status: "Available",
      icon: KeyRound,
      aliases: ["bastion", "jump host", "privileged access", "cbh", "audit"],
      searchCategory: "Security",
    },
    {
      name: "Cloud Firewall",
      shortName: "CFW",
      description: "Centralized traffic protection and access control.",
      href: "/services/cfw",
      logo: serviceLogos.CFW,
      status: "Available",
      icon: ShieldAlert,
      aliases: [
        "firewall",
        "cloud firewall",
        "eip protection",
        "vpc protection",
        "cfw",
      ],
      searchCategory: "Security",
    },
    {
      name: "Host Security Service",
      shortName: "HSS",
      description: "Server workload protection and host intrusion detection.",
      href: "/services/hss",
      logo: serviceLogos.HSS,
      status: "Available",
      icon: Server,
      aliases: [
        "host security",
        "agent",
        "vulnerability",
        "server risk",
        "baseline",
        "intrusion",
      ],
      searchCategory: "Security",
    },
    {
      name: "Anti-DDoS",
      shortName: "AAD",
      description: "DDoS mitigation for public network services.",
      logo: serviceLogos.AAD,
      status: "Catalog",
      icon: Boxes,
      aliases: [],
    },
    {
      name: "SecMaster",
      shortName: "SecMaster",
      description:
        "Security operations workspaces, views, and enterprise project boundaries.",
      href: "/services/secmaster",
      logo: serviceLogos.SECMASTER,
      status: "Available",
      icon: ShieldCheck,
      aliases: [
        "security operations",
        "workspace",
        "soc",
        "incident",
        "secmaster",
      ],
      searchCategory: "Security",
    },
    {
      name: "Workspace",
      shortName: "Workspace",
      description:
        "Cloud desktops, users, pools, tenant access, VPC placement, and security posture.",
      href: "/services/workspace",
      logo: serviceLogos.WORKSPACE,
      status: "Available",
      icon: Monitor,
      aliases: [
        "cloud desktop",
        "desktop",
        "workspace",
        "vdi",
        "enterprise id",
      ],
      searchCategory: "Security",
    },
  ],
  Billing: [
    {
      name: "Billing Center",
      shortName: "Billing",
      description:
        "Monthly account expenditure, refunds, coupons, and billing breakdowns.",
      href: "/services/billing/center",
      status: "Available",
      icon: Boxes,
      aliases: ["bills", "expenditure", "charges", "refunds"],
      searchCategory: "Billing",
    },
    {
      name: "Cost Center",
      shortName: "Cost",
      description:
        "Original and amortized net costs by service, region, or enterprise project.",
      href: "/services/cost",
      status: "Available",
      icon: Boxes,
      aliases: ["cost analysis", "spend", "amortized", "allocation"],
      searchCategory: "Billing",
    },
    {
      name: "Resource Packages",
      shortName: "Packages",
      description: "Prepaid resource packages and usage coverage.",
      href: "/services/packages",
      status: "Available",
      icon: Boxes,
      aliases: [],
    },
    {
      name: "Enterprise Project Management",
      shortName: "EPS",
      description:
        "Project-level resource grouping, accounting, and access control.",
      href: "/services/enterprise-projects",
      status: "Available",
      icon: Boxes,
      aliases: ["eps", "enterprise project", "governance", "cost allocation"],
      searchCategory: "Governance",
    },
  ],
  Monitoring: [
    {
      name: "Cloud Eye",
      shortName: "CES",
      description: "Metrics, alarms, dashboards, and resource monitoring.",
      href: "/services/ces",
      logo: serviceLogos.CES,
      status: "Available",
      icon: Activity,
      aliases: ["monitoring", "alarm", "metric", "observability"],
      searchCategory: "Monitoring",
    },
    {
      name: "Log Tank Service",
      shortName: "LTS",
      description:
        "Centralized log collection, search, analysis, and retention.",
      href: "/services/lts",
      logo: serviceLogos.LTS,
      status: "Available",
      icon: Logs,
      aliases: ["logs", "log group", "retention"],
      searchCategory: "Monitoring",
    },
    {
      name: "Application Operations Management",
      shortName: "AOM",
      description:
        "Prometheus instances, monitoring sources, retention, and enterprise-project ownership.",
      logo: serviceLogos.AOM,
      href: "/services/aom",
      status: "Available",
      icon: Boxes,
      aliases: ["aom", "prometheus", "metrics", "retention", "observability"],
    },
    {
      name: "Cloud Trace Service",
      shortName: "CTS",
      description: "Audit trail of cloud API and console operations.",
      href: "/services/cts",
      logo: serviceLogos.CTS,
      status: "Available",
      icon: ScrollText,
      aliases: ["audit", "trace", "tracker", "operations"],
      searchCategory: "Monitoring",
    },
    {
      name: "Simple Message Notification",
      shortName: "SMN",
      description:
        "Notification topics, subscriptions, and message delivery policies.",
      href: "/services/smn",
      logo: serviceLogos.SMN,
      status: "Available",
      icon: BellRing,
      aliases: ["notification", "topic", "subscription", "message", "pubsub"],
      searchCategory: "Monitoring",
    },
    {
      name: "IoT Device Access",
      shortName: "IoTDA",
      description:
        "Device registry status, product mapping, gateway relationship, and app space.",
      href: "/services/iotda",
      logo: serviceLogos.IOTDA,
      status: "Available",
      icon: RadioTower,
      aliases: [
        "iot",
        "iotda",
        "device access",
        "device registry",
        "gateway",
        "product",
      ],
      searchCategory: "IoT",
    },
    {
      name: "EventGrid",
      shortName: "EventGrid",
      description:
        "Event subscriptions, channels, source bindings, targets, and fanout posture.",
      href: "/services/eventgrid",
      logo: serviceLogos.EVENTGRID,
      status: "Available",
      icon: Cable,
      aliases: [
        "eventgrid",
        "event grid",
        "event subscription",
        "event channel",
        "event target",
      ],
      searchCategory: "Eventing",
    },
    {
      name: "KooGallery",
      shortName: "KooGallery",
      description:
        "Marketplace-facing purchased API rollup from APIG KooGallery subscription inventory.",
      href: "/services/koogallery",
      logo: serviceLogos.KOOGALLERY,
      status: "Available",
      icon: Store,
      aliases: [
        "koogallery",
        "marketplace",
        "purchased api",
        "api purchase",
        "subscription",
      ],
      searchCategory: "Marketplace",
    },
  ],
};

export const searchableServices = Object.entries(serviceCatalog).flatMap(
  ([category, services]) =>
    services
      .filter(
        (service): service is ServiceCatalogItem & { href: string } =>
          !!service.href,
      )
      .map((service) => ({
        ...service,
        category: service.searchCategory ?? category,
      })),
);

export function searchServices(query: string) {
  const term = query.toLowerCase().trim();
  return searchableServices.filter((service) =>
    [
      service.name,
      service.shortName,
      service.category,
      service.description,
      ...service.aliases,
    ].some((value) => value.toLowerCase().includes(term)),
  );
}
