import "server-only";
import { huaweiFetch } from "@/lib/huawei/http";
import { asRecord, firstString } from "@/lib/huawei/parsers";
import { listDewKeysForProject } from "@/lib/huawei/services/dew";
import { ManagementInputError } from "@/lib/management-contract";
import { cloudCacheKeys } from "@/lib/huawei/cache-keys";
import type { ManagementAdapter } from "../types";
const alias = { key: "alias", label: "Key alias", required: true, max: 255, pattern: "^[A-Za-z0-9:/_-]{1,255}$" };
export const dewManagement: ManagementAdapter = {
  title: "Data Encryption Workshop — KMS",
  operations: [
    { id: "create", label: "Create encryption key", kind: "create", description: "Create a symmetric AES-256 encryption key with key material generated inside KMS.", fields: [alias, { key: "description", label: "Description", type: "textarea", max: 255 }, { key: "enterpriseProjectId", label: "Enterprise project ID", defaultValue: "0", max: 64 }], impact: "KMS keys and API requests may incur charges according to this region's pricing." },
    { id: "alias", label: "Change key alias", kind: "update", description: "Rename a customer-managed key.", fields: [alias], allowedStatuses: ["1", "2"] },
    { id: "description", label: "Edit key description", kind: "update", description: "Change the customer-managed key description.", fields: [{ key: "description", label: "Description", type: "textarea", max: 255 }], allowedStatuses: ["1", "2"] },
    { id: "enable", label: "Enable key", kind: "action", description: "Enable a disabled key.", fields: [], allowedStatuses: ["2"] },
    { id: "disable", label: "Disable key", kind: "action", description: "Temporarily disable a customer-managed key.", fields: [], allowedStatuses: ["1"], confirmation: true, impact: "Resources and applications using this key can no longer encrypt or decrypt data while it is disabled." },
    { id: "rotation-enable", label: "Enable automatic rotation", kind: "action", description: "Enable rotation for a symmetric key generated by KMS.", fields: [], allowedStatuses: ["1"] },
    { id: "rotation-disable", label: "Disable automatic rotation", kind: "action", description: "Stop automatically rotating new key material.", fields: [], allowedStatuses: ["1"] },
    { id: "rotation-status", label: "View rotation status", kind: "inspect", description: "Read the automatic rotation configuration.", fields: [] },
    { id: "schedule-delete", label: "Schedule key deletion", kind: "delete", description: "Disable the key and schedule its permanent removal after a waiting period.", fields: [{ key: "days", label: "Waiting period (days)", type: "number", required: true, min: 7, max: 1096, defaultValue: 30 }], allowedStatuses: ["1", "2"], confirmation: true, impact: "The key becomes unusable during the waiting period. After deletion, encrypted data depending on this key cannot be recovered." },
    { id: "cancel-delete", label: "Cancel key deletion", kind: "action", description: "Cancel pending permanent deletion; enable the key separately after cancellation.", fields: [], allowedStatuses: ["3"] },
  ],
  inventory: async (session) => (await listDewKeysForProject(session)).map((key) => ({ id: key.id, name: key.alias, status: key.keyState, values: { alias: key.alias, origin: key.origin, keyType: key.keyType, keySpec: key.keySpec, defaultKey: key.defaultKey } })),
  invalidationKeys: () => [cloudCacheKeys.listDewKeys],
  execute: async (session, operation, values, resource) => {
    if (resource && operation !== "rotation-status" && (resource.values?.defaultKey === true || /^(obs|evs|rds|sfs|cbr|dms|kms|csms)\/default$/i.test(resource.name))) throw new ManagementInputError("This is a cloud service's default key. Manage customer-created keys through this workflow.", 409);
    if (operation.startsWith("rotation-") && operation !== "rotation-status" && (resource?.values?.origin !== "kms" || !["AES_256", "SM4", "SYMMETRIC_DEFAULT"].includes(String(resource?.values?.keySpec)))) throw new ManagementInputError("Automatic rotation requires a supported symmetric key generated by KMS.", 409);
    const paths: Record<string, string> = { create: "create-key", alias: "update-key-alias", description: "update-key-description", enable: "enable-key", disable: "disable-key", "rotation-enable": "enable-key-rotation", "rotation-disable": "disable-key-rotation", "rotation-status": "get-key-rotation-status", "schedule-delete": "schedule-key-deletion", "cancel-delete": "cancel-key-deletion" };
    if (!Object.hasOwn(paths, operation)) throw new ManagementInputError("Unsupported KMS operation.");
    const body = operation === "create" ? { key_alias: values.alias, key_spec: "AES_256", key_usage: "ENCRYPT_DECRYPT", origin: "kms", key_description: values.description ?? "", enterprise_project_id: values.enterpriseProjectId ?? "0" } : { key_id: resource!.id, ...(operation === "alias" ? { key_alias: values.alias } : operation === "description" ? { key_description: values.description ?? "" } : operation === "schedule-delete" ? { pending_days: String(values.days) } : {}) };
    const result = await huaweiFetch<Record<string, unknown>>(session, "dew", `/v1.0/${session.projectId}/kms/${paths[operation]}`, { method: "POST", body: JSON.stringify(body) });
    if (operation === "rotation-status") return { message: "Key rotation status loaded.", facts: [{ label: "Automatic rotation", value: result.key_rotation_enabled === true ? "Enabled" : "Disabled" }, { label: "Rotation interval", value: `${result.rotation_interval ?? "Not reported"} days` }] };
    return { message: operation === "schedule-delete" ? "Key deletion scheduled. The key is unavailable during the waiting period." : "KMS key operation completed.", resourceId: firstString([asRecord(result.key_info).key_id, result.key_id, resource?.id], "") || undefined };
  },
};
