import type { MetadataRoute } from "next";

const siteUrl = "https://ui.hwctools.site";

const routes = [
  "/",
  "/services/apig",
  "/services/aom",
  "/services/as",
  "/services/billing",
  "/services/bms",
  "/services/cbr",
  "/services/cbh",
  "/services/cce",
  "/services/cdn",
  "/services/ces",
  "/services/cfw",
  "/services/compute",
  "/services/containers",
  "/services/cph",
  "/services/css",
  "/services/cts",
  "/services/dataarts",
  "/services/databases",
  "/services/dcs",
  "/services/dds",
  "/services/deh",
  "/services/dew",
  "/services/direct-connect",
  "/services/dli",
  "/services/dms-kafka",
  "/services/dms-rabbitmq",
  "/services/dms-rocketmq",
  "/services/dns",
  "/services/drs",
  "/services/dws",
  "/services/ecs",
  "/services/eip",
  "/services/elb",
  "/services/enterprise-router",
  "/services/enterprise-projects",
  "/services/eventgrid",
  "/services/evs",
  "/services/flexus",
  "/services/functiongraph",
  "/services/gaussdb",
  "/services/geminidb",
  "/services/hss",
  "/services/iam",
  "/services/ims",
  "/services/iotda",
  "/services/koogallery",
  "/services/lts",
  "/services/mgc",
  "/services/modelarts",
  "/services/monitoring",
  "/services/mrs",
  "/services/nat",
  "/services/network",
  "/services/networking",
  "/services/obs",
  "/services/oms",
  "/services/rds",
  "/services/sdrs",
  "/services/secmaster",
  "/services/security",
  "/services/servicestage",
  "/services/sfs",
  "/services/smn",
  "/services/sms",
  "/services/storage",
  "/services/swr",
  "/services/taurusdb",
  "/services/vpc-endpoint",
  "/services/vpn",
  "/services/waf",
  "/services/workspace",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route, index) => ({
    url: `${siteUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: index === 0 ? 1 : 0.7,
  }));
}
