/** Stable keys shared by readers and mutations; never derive these from function names. */
export const cloudCacheKeys = {
  summary: "cloud-summary",
  listAomPrometheusInstances: "listAomPrometheusInstances",
  listEnterpriseProjects: "listEnterpriseProjects",
  listDmsRabbitMqInstances: "listDmsRabbitMqInstances",
  listDmsRocketMqInstances: "listDmsRocketMqInstances",
  messagingInstance: (
    engine: "rabbitmq" | "rocketmq",
    id: string,
    projectId?: string,
  ) =>
    JSON.stringify([
      "messaging-instance-v1",
      engine,
      projectId ?? "default",
      id,
    ]),
  listAsGroups: "listAsGroups",
  listSwrRepositories: "listSwrRepositories",
  asGroup: (id: string) => `as-group-v1:${id}`,
  swrRepository: (id: string) => `swr-repository-v1:${id}`,
  billing: (month: string) => `billing-summary-v1:${month}`,
  costs: (month: string, group: string, type: string) =>
    `cost-analysis-v1:${month}:${group}:${type}`,
  listApigInstances: "listApigInstances",
  listBmsServers: "listBmsServers",
  listCbhInstances: "listCbhInstances",
  listCbrVaults: "listCbrVaults",
  listCceClusters: "listCceClusters",
  listCciNamespaces: "listCciNamespaces",
  listCdmClusters: "listCdmClusters",
  listCdnDomains: "listCdnDomains",
  listCesAlarmRules: "listCesAlarmRules",
  listCloudFirewalls: "listCloudFirewalls",
  listCodeArtsBuildJobs: "listCodeArtsBuildJobs",
  listCodeArtsDeployApplications: "listCodeArtsDeployApplications",
  listCodeArtsPipelines: "listCodeArtsPipelines",
  listCodeArtsRepositories: "listCodeArtsRepositories",
  listCphServers: "listCphServers",
  listCssClusters: "listCssClusters",
  listCtsTrackers: "listCtsTrackers",
  listDataArtsInstances: "listDataArtsInstances",
  listDcsRedisInstances: "listDcsRedisInstances",
  listDdsInstances: "listDdsInstances",
  listDedicatedHosts: "listDedicatedHosts",
  listDewKeys: "listDewKeys",
  listDirectConnectConnections: "listDirectConnectConnections",
  listDliQueues: "listDliQueues",
  listDmsKafkaInstances: "listDmsKafkaInstances",
  listDnsZones: "listDnsZones",
  listDrsJobs: "listDrsJobs",
  listDwsClusters: "listDwsClusters",
  listEcsInstances: "listEcsInstances",
  listEips: "listEips",
  listElbs: "listElbs",
  listEnterpriseRouters: "listEnterpriseRouters",
  listEventGridSubscriptions: "listEventGridSubscriptions",
  listEvsDisks: "listEvsDisks",
  listFlexusResources: "listFlexusResources",
  listFunctionGraphFunctions: "listFunctionGraphFunctions",
  listGaussDbInstances: "listGaussDbInstances",
  listGeminiDbInstances: "listGeminiDbInstances",
  listHssHosts: "listHssHosts",
  listIamUsers: "listIamUsers",
  listImages: "listImages",
  listIotdaDevices: "listIotdaDevices",
  listKooGalleryPurchasedApis: "listKooGalleryPurchasedApis",
  listLtsLogGroups: "listLtsLogGroups",
  listMgcMigrationItems: "listMgcMigrationItems",
  listModelArtsNotebooks: "listModelArtsNotebooks",
  listMrsClusters: "listMrsClusters",
  listNatSnatRules: "listNatSnatRules",
  listNatGateways: "listNatGateways",
  listObsBuckets: "listObsBuckets",
  listOmsMigrationTasks: "listOmsMigrationTasks",
  listRdsInstances: "listRdsInstances",
  listSdrsProtectedInstances: "listSdrsProtectedInstances",
  listSecMasterWorkspaces: "listSecMasterWorkspaces",
  listSecurityGroups: "listSecurityGroups",
  listServiceStageApplications: "listServiceStageApplications",
  listSfsShares: "listSfsShares",
  listSmnTopics: "listSmnTopics",
  listSmsTasks: "listSmsTasks",
  listSubnets: "listSubnets",
  listTaurusDbInstances: "listTaurusDbInstances",
  listVpcEndpoints: "listVpcEndpoints",
  listVpcs: "listVpcs",
  listVpnConnections: "listVpnConnections",
  listWafInstances: "listWafInstances",
  listWorkspaceTenants: "listWorkspaceTenants",
  ecs: (id: string) => `ecs-instance-v2:${id}`,
  ecsMonitoring: (id: string) => `ecs-monitoring-v3:${id}`,
  ecsSnapshots: (id: string) => `ecs-snapshots:${id}`,
  obsBucket: (bucket: string) => `obs-bucket:${bucket}`,
  obsObject: (bucket: string, key: string) => `obs-object:${bucket}:${key}`,
  evs: (id: string) => `evs-disk:${id}`,
  rds: (id: string) => `rds-instance:${id}`,
  elb: (id: string) => `elb:${id}`,
  dds: (id: string) => `dds-instance:${id}`,
  gaussDb: (id: string) => `gaussdb-instance:${id}`,
  taurusDb: (id: string) => `taurusdb-instance:${id}`,
  functionGraphTriggers: "functiongraph-triggers",
  cce: (id: string) => `cce-cluster:${id}`,
  functionGraphCode: (id: string) => `functiongraph-function-code-v4:${id}`,
  functionGraph: (id: string) => `functiongraph-function:${id}`,
  vpc: (id: string) => `vpc:${id}`,
  subnet: (id: string) => `subnet:${id}`,
  securityGroup: (id: string) => `security-group:${id}`,
} as const;
